# Generated by Django 3.2.16 on 2022-12-18 19:04

import GraphQL.models.methods
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entity', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Entity.entity')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branchs',
            },
            bases=('Entity.entity', models.Model),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('image', models.ImageField(blank=True, default='images/{instance.__class__.__name__}/default.jpg', null=True, upload_to=GraphQL.models.methods.upload_to, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Entity.entity')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
            bases=('Entity.entity',),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='MobileNetWork',
            fields=[
                ('facility_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Facility.facility')),
                ('tel_code', models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Telephone Code')),
            ],
            options={
                'verbose_name': 'Mobile NetWork',
                'verbose_name_plural': 'Mobile NetWorks',
            },
            bases=('Facility.facility',),
        ),
        migrations.CreateModel(
            name='PublicFacility',
            fields=[
                ('facility_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Facility.facility')),
                ('facility_type', models.CharField(choices=[('L', 'Laboratory'), ('ML', 'Main Laboratory'), ('A', 'Association'), ('D', 'Dispensary'), ('SC', 'Scientific Company'), ('P', 'Pharmaceutical Company'), ('S', 'Supplier'), ('DC', 'Dental Clinic'), ('PC', 'Private Clinic'), ('B', 'Butcher'), ('G', 'Grocery'), ('Ba', 'Barber'), ('Ph', 'Pharmacy'), ('MF', 'Medical Facility'), ('DA', 'Dispensary & Associations')], max_length=35, verbose_name='Facility Type')),
            ],
            options={
                'verbose_name': 'Public Facility',
                'verbose_name_plural': 'Public Facilities',
            },
            bases=('Facility.facility',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('owner_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stores', to='Facility.facility', verbose_name='Owner Facility')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('week_day', models.CharField(choices=[('Sat', 'Monday'), ('Sun', 'Tuesday'), ('Mon', 'Wednesday'), ('Tue', 'Thursday'), ('Wed', 'Friday'), ('Thu', 'Saturday'), ('Fri', 'Sunday')], max_length=10, verbose_name='Week Day')),
                ('day_part', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening')], max_length=4, verbose_name='Day Part')),
                ('attending_time', models.TimeField(verbose_name='Attending Time')),
                ('leaving_time', models.TimeField(verbose_name='Leaving Time')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_facility.shift_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
            },
        ),
    ]
