# Generated by Django 3.2.16 on 2022-12-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
        ('Facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='made_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Made Brands+', to='Location.country', verbose_name='Made In'),
        ),
        migrations.AddField(
            model_name='branch',
            name='owning_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Branchs', to='Facility.facility', verbose_name='Owning Facility'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('week_day', 'day_part')},
        ),
    ]
