# Generated by Django 3.2.16 on 2022-12-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Facility', '0002_initial'),
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfacility',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Facilities', to='Person.person', verbose_name='Owner'),
        ),
    ]
