# Generated by Django 3.2.16 on 2022-12-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payment', '0001_initial'),
        ('Location', '0001_initial'),
        ('Facility', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Countries', to='Payment.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(related_name='Countries', to='Language.Language', verbose_name='languages'),
        ),
        migrations.AddField(
            model_name='communicationway',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_location.communicationway_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cities', to='Location.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cities', to='Location.governorate', verbose_name='Governorate'),
        ),
        migrations.AddField(
            model_name='phone',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Phones', to='Location.country', verbose_name='Country Code'),
        ),
        migrations.AddField(
            model_name='email',
            name='server',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_email': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Location.socialmedia', verbose_name='Server'),
        ),
        migrations.AddField(
            model_name='email',
            name='socila_media',
            field=models.ManyToManyField(to='Location.SocialMedia', verbose_name='Social Medias'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='Location.street', verbose_name='Street'),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Location.phone')),
                ('has_cach_pyment', models.BooleanField(default=False, verbose_name='has Cach Pyment')),
                ('netWork_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mobiles', to='Facility.mobilenetwork', verbose_name='NetWork Code')),
                ('socila_media', models.ManyToManyField(to='Location.SocialMedia', verbose_name='Social Medias')),
            ],
            options={
                'verbose_name': 'Mobile',
                'verbose_name_plural': 'Mobiles',
            },
            bases=('Location.phone',),
        ),
        migrations.CreateModel(
            name='LandPhone',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Location.phone')),
                ('governorate_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LandPhones', to='Location.governorate', to_field='tel_code', verbose_name='Governorate Code')),
            ],
            options={
                'verbose_name': 'Land Phone',
                'verbose_name_plural': 'Land Phones',
            },
            bases=('Location.phone',),
        ),
    ]
