# Generated by Django 3.2.16 on 2022-12-18 07:06

import GraphQL.models.methods
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='images/{instance.__class__.__name__}/default.jpg', null=True, upload_to=GraphQL.models.methods.upload_to, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(verbose_name='Volume')),
                ('serial', models.CharField(max_length=50, unique=True, verbose_name='Serial No.')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('discount_price', models.FloatField(default=0, verbose_name='Discount Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Discrption')),
                ('currency', models.ForeignKey(default='EGP', on_delete=django.db.models.deletion.CASCADE, related_name='Invoices', to='Payment.currency', verbose_name='Currency')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product Item')),
            ],
            options={
                'verbose_name': 'ProductPackaging',
                'verbose_name_plural': 'ProductPackaging',
            },
        ),
    ]
