# Generated by Django 3.2.16 on 2022-12-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalTechnique',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Technique Method',
                'verbose_name_plural': 'Technique Methods',
            },
        ),
    ]
