# Generated by Django 3.2.16 on 2022-12-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Specimen', '0001_initial'),
        ('Product', '0001_initial'),
        ('Analytic', '0003_initial'),
        ('Kat', '0002_initial'),
        ('Unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Standards', to='Unit.unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='katsample',
            name='kat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kat.kat', verbose_name='Kat'),
        ),
        migrations.AddField(
            model_name='kat',
            name='analytical_technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kats', to='Kat.analyticaltechnique', verbose_name='Analytical Technique'),
        ),
        migrations.AddField(
            model_name='kat',
            name='analytics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kats', to='Analytic.analytics', verbose_name='Analytics'),
        ),
        migrations.AddField(
            model_name='kat',
            name='analyzers',
            field=models.ManyToManyField(through='Kat.AnalyzerKat', to='Kat.Analyzer', verbose_name='Analyzers'),
        ),
        migrations.AddField(
            model_name='kat',
            name='samples',
            field=models.ManyToManyField(through='Kat.KatSample', to='Specimen.Sample', verbose_name='Samples'),
        ),
        migrations.AddField(
            model_name='antibioticdisk',
            name='anti_biotic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Anti_Biotic_Disks', to='Product.product', verbose_name='Anti-Biotic'),
        ),
        migrations.AddField(
            model_name='analyzerkat',
            name='kat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kat.kat', verbose_name='Analyzer'),
        ),
        migrations.AlterUniqueTogether(
            name='katsample',
            unique_together={('kat', 'sample')},
        ),
        migrations.AlterUniqueTogether(
            name='analyzerkat',
            unique_together={('analyzer', 'kat')},
        ),
    ]
