# Generated by Django 3.2.16 on 2022-12-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('native', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Native')),
                ('symbol', models.CharField(max_length=3, unique=True, verbose_name='Symbol')),
                ('last_update', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='FinancialItem',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('item_type', models.CharField(choices=[('R', 'Revenue Item'), ('E', 'Expense Item')], max_length=1, verbose_name='Financial Item Type')),
            ],
            options={
                'verbose_name': 'Financial Item',
                'verbose_name_plural': 'Financial Items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Ch', 'Check'), ('P', 'PayPal'), ('S', 'Stripe'), ('Ca', 'Cach')], max_length=2, verbose_name='Payment Method')),
                ('charge_id', models.CharField(max_length=50, unique=True, verbose_name='Charge ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='Payment Time')),
                ('currency', models.ForeignKey(default='EGP', on_delete=django.db.models.deletion.CASCADE, related_name='Payments', to='Payment.currency', verbose_name='Currency')),
                ('financial_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Payments', to='Payment.financialitem', verbose_name='FinancialItem')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_payment.payment_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PeriodicFinancialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic_time', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly'), ('A', 'Any')], max_length=2, verbose_name='Periodic Time')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('currency', models.ForeignKey(default='EGP', on_delete=django.db.models.deletion.CASCADE, related_name='Financials', to='Payment.currency', verbose_name='Currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment.financialitem', verbose_name='Financial Item')),
            ],
            options={
                'verbose_name': 'Periodic Financial Item',
                'verbose_name_plural': 'Periodic Financial Items',
            },
        ),
        migrations.CreateModel(
            name='PeriodicPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Payment.payment')),
                ('periodic_financial_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payments', to='Payment.periodicfinancialitem', verbose_name='Periodic Financial Item')),
            ],
            options={
                'verbose_name': 'Periodic Item',
                'verbose_name_plural': 'Periodic Items',
            },
            bases=('Payment.payment',),
        ),
    ]
