# Generated by Django 3.2.16 on 2022-12-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Kat', '0002_initial'),
        ('Invoice', '0003_initial'),
        ('Laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='lab_supply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Kat.labsupply', verbose_name='Laboratory Supply'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_details',
            field=models.ManyToManyField(related_name='Stocks', to='Invoice.LineInInvoice', verbose_name='Product Details'),
        ),
    ]
