# Generated by Django 3.2.16 on 2022-12-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('native', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Native')),
                ('symbol', models.CharField(max_length=2, unique=True, verbose_name='Symbol')),
                ('power', models.IntegerField(verbose_name='Power')),
            ],
            options={
                'verbose_name': 'Prefix',
                'verbose_name_plural': 'Prefixes',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('native', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Native')),
                ('symbol', models.CharField(max_length=5, unique=True, verbose_name='Symbol')),
                ('measurement', models.CharField(choices=[('P', 'Package'), ('V', 'Volume'), ('A', 'Area'), ('L', 'Length'), ('M', 'Mass'), ('C', 'Concentation'), ('S', 'Speed'), ('T', 'Time'), ('D', 'Direction'), ('Te', 'Temperature'), ('EC', 'Electric Current'), ('LI', 'Luminous Intensity')], max_length=2, verbose_name='Measurement')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='OriginalUnit',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Unit.unit')),
                ('international_system_unit', models.CharField(choices=[('CGS', 'Cgs'), ('MKS', 'Mks')], max_length=4, verbose_name='International System Unit')),
            ],
            options={
                'verbose_name': 'Original Unit',
                'verbose_name_plural': 'Original Units',
            },
            bases=('Unit.unit',),
        ),
        migrations.CreateModel(
            name='UnitConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Equation')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coverted_Units', to='Unit.unit', verbose_name='to Unit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unit.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Unit Convert',
                'verbose_name_plural': 'Units Convert',
                'unique_together': {('unit', 'to_unit')},
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='convert_to',
            field=models.ManyToManyField(related_name='_Unit_unit_convert_to_+', through='Unit.UnitConvert', to='Unit.Unit', verbose_name='Convert To'),
        ),
        migrations.AddField(
            model_name='unit',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_unit.unit_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('category_parent', models.ForeignKey(blank=True, limit_choices_to={'category_parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sub Categories+', to='Unit.category', verbose_name='Category Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ComplexUnit',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Unit.unit')),
                ('power', models.SmallIntegerField(blank=True, null=True, verbose_name='Power')),
                ('divide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Divide_Units', to='Unit.unit', verbose_name='Divide')),
                ('multiply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Multiply_Units', to='Unit.unit', verbose_name='Multiply')),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Units', to='Unit.prefix', verbose_name='Prefix')),
            ],
            options={
                'verbose_name': 'Complex Unit',
                'verbose_name_plural': 'Complex Units',
            },
            bases=('Unit.unit',),
        ),
    ]
