# Generated by Django 3.2.16 on 2022-12-18 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending_time', models.TimeField(verbose_name='Attending Time')),
                ('leaving_time', models.TimeField(verbose_name='Leaving Time')),
            ],
            options={
                'verbose_name': 'Laboratory Attendance',
                'verbose_name_plural': 'Laboratory Attendances',
            },
        ),
        migrations.CreateModel(
            name='Bonuss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('reason', models.TextField()),
            ],
            options={
                'verbose_name': 'Bonuss',
                'verbose_name_plural': 'Bonusss',
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('reason', models.TextField()),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
            },
        ),
    ]
