# Generated by Django 3.2.16 on 2022-12-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('Employee', '0001_initial'),
        ('Analysis', '0002_initial'),
        ('Facility', '0003_publicfacility_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.person')),
                ('salary', models.FloatField(verbose_name='Salary')),
                ('allowed_discount_rate', models.FloatField(default=5.0, verbose_name='Allowed Discount Rate')),
                ('shifts', models.ManyToManyField(related_name='Employees', to='Facility.Shift', verbose_name='Shifts')),
                ('work_in_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employees', to='Facility.branch', verbose_name='Work in Branch')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'permissions': [('set_published_status', 'Can set the status of the post to either publish or not')],
            },
            bases=('Person.person',),
        ),
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DateTimeField(auto_now_add=True, verbose_name='Execution Time')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employee_Activities', to='Employee.activity', verbose_name='Activity')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee', verbose_name='Employee')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_employee.employeeactivity_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Employee Activity',
                'verbose_name_plural': 'Employee Activities',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateField(verbose_name='Date')),
                ('is_accepted', models.BooleanField(default=True, verbose_name='is_Accepted')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vacations', to='Employee.employee', verbose_name='Employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facility.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Vacation',
                'verbose_name_plural': 'Vacations',
            },
        ),
        migrations.AddField(
            model_name='deduction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Deductions', to='Employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='bonuss',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bonusss', to='Employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attendances', to='Employee.employee', verbose_name='Employee'),
        ),
        migrations.CreateModel(
            name='ReportEmployeeActivity',
            fields=[
                ('employeeactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Employee.employeeactivity')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee_Activities', to='Analysis.report', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Report Employee Activity',
                'verbose_name_plural': 'Report Employee Activities',
            },
            bases=('Employee.employeeactivity',),
        ),
    ]
