# Generated by Django 3.2.16 on 2022-12-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('molecular_weight', models.SmallIntegerField(blank=True, null=True, verbose_name='Molecular Weight')),
                ('chemical_structure', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chemical Structure')),
            ],
            options={
                'verbose_name': 'Analytics',
                'verbose_name_plural': 'Analytics',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=True, verbose_name='Is Default')),
            ],
            options={
                'verbose_name': 'Analytics Unit',
                'verbose_name_plural': 'Analytics Units',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsUnitConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.BooleanField(verbose_name='Factor')),
            ],
            options={
                'verbose_name': 'Analytics Unit Convert',
                'verbose_name_plural': 'Analytics Unit Converts',
            },
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('lowest_value', models.FloatField(blank=True, null=True, verbose_name='Lowest Value')),
                ('highest_value', models.FloatField(blank=True, null=True, verbose_name='Highest Value')),
            ],
            options={
                'verbose_name': 'Reference Range',
                'verbose_name_plural': 'Reference Ranges',
            },
        ),
        migrations.CreateModel(
            name='ReferenceRangeExpectedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_normal', models.FloatField(blank=True, null=True, verbose_name='Minimum Normal')),
                ('max_normal', models.FloatField(blank=True, null=True, verbose_name='Maximum Normal')),
            ],
            options={
                'verbose_name': 'Reference Range Expected Value',
                'verbose_name_plural': 'Reference Range Expected Values',
            },
        ),
    ]
