# Generated by Django 3.2.16 on 2022-12-18 19:04

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Specimen', '0001_initial'),
        ('Person', '0001_initial'),
        ('Analytic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencerangeexpectedvalue',
            name='reference_limiting_factors',
            field=models.ManyToManyField(to='Person.ReferenceLimitingFactor', verbose_name='Reference Limiting Factors'),
        ),
        migrations.AddField(
            model_name='referencerangeexpectedvalue',
            name='reference_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_range_expected_values+', to='Analytic.referencerange', verbose_name='ReferenceRange'),
        ),
        migrations.AddField(
            model_name='referencerange',
            name='analytics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reference_Ranges', to='Analytic.analytics', verbose_name='Analytics'),
        ),
        migrations.AddField(
            model_name='referencerange',
            name='reference_range_expected_values',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='Analytic.referencerangeexpectedvalue', verbose_name='Reference Range Expected Values'),
        ),
        migrations.AddField(
            model_name='referencerange',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reference_Ranges', to='Specimen.sample', verbose_name='Sample'),
        ),
    ]
