# Generated by Django 3.2.16 on 2022-12-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectiveMaterial',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Effective Material',
                'verbose_name_plural': 'Effective Materials',
            },
        ),
        migrations.CreateModel(
            name='PharmaceuticalForm',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Pharmaceutical Form',
                'verbose_name_plural': 'Pharmaceutical Forms',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('for_child_pregnant', models.BooleanField(verbose_name='for Child Pregnant')),
                ('trade_name', models.CharField(max_length=25, unique=True, verbose_name='Trade Name')),
                ('effective_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Drugs', to='Drug.effectivematerial', verbose_name='Effective Material')),
                ('pharmaceutical_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Drugs', to='Drug.pharmaceuticalform', verbose_name='Pharmaceutical Form')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
            },
            bases=('Product.product',),
        ),
    ]
