# Generated by Django 3.2.16 on 2022-12-18 07:06

import GraphQL.custom_fields
import GraphQL.models.methods
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Analysis', '0002_initial'),
        ('Employee', '0002_initial'),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineInReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=40, verbose_name='Result')),
            ],
            options={
                'verbose_name': 'Line In Report',
                'verbose_name_plural': 'Lines In Reports',
            },
        ),
        migrations.CreateModel(
            name='PaymentEmployeeActivity',
            fields=[
                ('employeeactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Employee.employeeactivity')),
            ],
            options={
                'verbose_name': 'Payment Employee Activity',
                'verbose_name_plural': 'Payment Employee Activities',
            },
            bases=('Employee.employeeactivity',),
        ),
        migrations.CreateModel(
            name='Phlebotomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phlebotomy_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Phlebotomy Time')),
                ('is_external_phlebotomy', models.BooleanField(default=False, verbose_name='is Phlebotomy Time')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PhlebotomyEmployeeActivity',
            fields=[
                ('employeeactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Employee.employeeactivity')),
            ],
            options={
                'verbose_name': 'Phlebotomy Employee Activity',
                'verbose_name_plural': 'Phlebotomy Employee Activities',
            },
            bases=('Employee.employeeactivity',),
        ),
        migrations.CreateModel(
            name='PhlebotomySpecimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_take_outSide', models.BooleanField(default=False, verbose_name='is Taken Out Side')),
            ],
            options={
                'verbose_name': 'Phlebotomy Specimen',
                'verbose_name_plural': 'Phlebotomy Specimens',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('image', models.ImageField(blank=True, default='images/{instance.__class__.__name__}/default.jpg', null=True, upload_to=GraphQL.models.methods.upload_to, verbose_name='Image')),
                ('bar_code', GraphQL.custom_fields.BarCodeField(max_length=24, primary_key=True, serialize=False, verbose_name='BarCode')),
                ('phlebotomy_required_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Phlebotomy Required Time')),
                ('expected_receipt_time', models.DateTimeField(blank=True, null=True, verbose_name='Expected Receipt Time')),
                ('discount', models.FloatField(default=0, verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionEmployeeActivity',
            fields=[
                ('employeeactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Employee.employeeactivity')),
            ],
            options={
                'verbose_name': 'Prescription Employee Activity',
                'verbose_name_plural': 'Prescription Employee Activities',
            },
            bases=('Employee.employeeactivity',),
        ),
        migrations.CreateModel(
            name='PrescriptionPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Payment.payment')),
            ],
            options={
                'verbose_name': 'Prescription Payment',
                'verbose_name_plural': 'Prescription Payments',
            },
            bases=('Payment.payment',),
        ),
        migrations.CreateModel(
            name='PrescriptionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Prescription Report',
                'verbose_name_plural': 'Prescription Reports',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionReportImage',
            fields=[
                ('analysis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Analysis.analysis')),
                ('image', models.ImageField(blank=True, default='images/{instance.__class__.__name__}/default.jpg', null=True, upload_to=GraphQL.models.methods.upload_to, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Prescription Report Image',
                'verbose_name_plural': 'Prescription Report Images',
            },
            bases=('Analysis.analysis', models.Model),
        ),
        migrations.CreateModel(
            name='PrescriptionVitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Prescription Vital Sign',
                'verbose_name_plural': 'Prescription Vital Signs',
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Maximum Value')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Minimum Value')),
                ('low_normal_value', models.FloatField(blank=True, null=True, verbose_name='Low Normal Value')),
                ('high_normal_value', models.FloatField(blank=True, null=True, verbose_name='High Normal Value')),
            ],
            options={
                'verbose_name': 'Vital Sign',
                'verbose_name_plural': 'Vital Signs',
            },
        ),
    ]
