# Generated by Django 3.2.16 on 2022-12-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Entity', '0002_initial'),
        ('Facility', '0002_initial'),
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kinship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister')], max_length=20, verbose_name='Relation')),
            ],
            options={
                'verbose_name': 'Kinship',
                'verbose_name_plural': 'Kinships',
            },
        ),
        migrations.CreateModel(
            name='ReferenceLimitingFactor',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('emoji', models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Emoji')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Category', to='Person.referencelimitingfactor', verbose_name='Category')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_person.referencelimitingfactor_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Reference Limiting Factor',
                'verbose_name_plural': 'Reference Limiting Factors',
            },
        ),
        migrations.CreateModel(
            name='AgeStage',
            fields=[
                ('referencelimitingfactor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.referencelimitingfactor')),
            ],
            options={
                'verbose_name': 'Age Stage',
                'verbose_name_plural': 'Age Stages',
            },
            bases=('Person.referencelimitingfactor',),
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('referencelimitingfactor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.referencelimitingfactor')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
            },
            bases=('Person.referencelimitingfactor',),
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('referencelimitingfactor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.referencelimitingfactor')),
                ('is_active', models.BooleanField(default=False, verbose_name='is Active')),
            ],
            options={
                'verbose_name': 'Marital Status',
                'verbose_name_plural': 'Marital Status',
            },
            bases=('Person.referencelimitingfactor',),
        ),
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('referencelimitingfactor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.referencelimitingfactor')),
            ],
            options={
                'verbose_name': 'Menstrual Cycle',
                'verbose_name_plural': 'Menstrual Cycles',
            },
            bases=('Person.referencelimitingfactor',),
        ),
        migrations.CreateModel(
            name='SamplingEating',
            fields=[
                ('referencelimitingfactor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.referencelimitingfactor')),
            ],
            options={
                'verbose_name': 'Correlation of sampling with eating',
                'verbose_name_plural': 'Correlation of sampling with eatings',
            },
            bases=('Person.referencelimitingfactor',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Entity.entity')),
                ('national_id', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='National ID')),
                ('family_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Family Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('Job', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Deleted'), to='Facility.job', verbose_name='Job')),
                ('kinshipers', models.ManyToManyField(related_name='_Person_person_kinshipers_+', through='Person.Kinship', to='Person.Person', verbose_name='Kinshipers')),
                ('language', models.ForeignKey(blank=True, default='ar', null=True, on_delete=models.SET('Deleted'), related_name='Persons', to='Language.language', verbose_name='Language')),
                ('gender', models.ForeignKey(on_delete=models.SET('Deleted'), to='Person.gender', verbose_name='Gender')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Deleted'), to='Person.maritalstatus', verbose_name='Marital Status')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
            bases=('Entity.entity',),
        ),
        migrations.AddField(
            model_name='kinship',
            name='kinshiper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person', verbose_name='Kinshiper'),
        ),
        migrations.AddField(
            model_name='kinship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinshipers+', to='Person.person', verbose_name='Person'),
        ),
        migrations.AlterUniqueTogether(
            name='kinship',
            unique_together={('person', 'kinshiper')},
        ),
    ]
