# Generated by Django 3.2.16 on 2022-12-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
        ('Entity', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitycommunicationway',
            name='communication_way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entities', to='Location.communicationway', verbose_name='Communication Way'),
        ),
        migrations.AddField(
            model_name='entitycommunicationway',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.entity', verbose_name='Entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='communication_ways',
            field=models.ManyToManyField(through='Entity.EntityCommunicationWay', to='Location.CommunicationWay', verbose_name='Communication Ways'),
        ),
        migrations.AddField(
            model_name='entity',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_entity.entity_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='entitycommunicationway',
            unique_together={('entity', 'communication_way')},
        ),
    ]
