# Generated by Django 3.2.16 on 2022-12-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('serial_no', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Serial Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cearted At')),
                ('received_date', models.DateTimeField(auto_now_add=True, verbose_name='Received Date')),
                ('is_received', models.BooleanField(default=False, verbose_name='is Received')),
                ('is_refund_requested', models.BooleanField(default=False, verbose_name='is Refund Requested')),
                ('is_refund_granted', models.BooleanField(default=False, verbose_name='is Refund Granted')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Business',
            },
        ),
    ]
