# Generated by Django 3.2.16 on 2022-12-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Invoice', '0002_businesspayment_coupon_invoice_lineininvoice_order_refund'),
        ('Employee', '0002_initial'),
        ('Payment', '0001_initial'),
        ('Location', '0002_initial'),
        ('Product', '0001_initial'),
        ('Person', '0001_initial'),
        ('Facility', '0003_publicfacility_owner'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineininvoice',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lines_In_Invoices', to='Product.productpackaging', verbose_name='Product Item'),
        ),
        migrations.AddField(
            model_name='businesspayment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payments', to='Invoice.business', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='business',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Invoice.coupon', verbose_name='Coupon'),
        ),
        migrations.AddField(
            model_name='business',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='Payment.payment', verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='business',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_invoice.business_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='business',
            name='products_items',
            field=models.ManyToManyField(through='Invoice.LineInInvoice', to='Product.ProductPackaging', verbose_name='Products Items'),
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Refunds', to='Invoice.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='Location.address', verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='Location.address', verbose_name='Shipping Address'),
        ),
        migrations.AlterUniqueTogether(
            name='lineininvoice',
            unique_together={('invoice', 'product_item')},
        ),
        migrations.AddField(
            model_name='invoice',
            name='employee',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), related_name='Invoices', to='Employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'supplier': 'S'}, on_delete=models.SET('Deleted'), related_name='Invoices', to='Facility.facility', verbose_name='Supplier'),
        ),
    ]
